eureka:
    client:
        registry-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8082
spring:
    application:
        name: customer-service
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true

